# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_auto_20161216_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='num',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
