# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_membership_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='num',
        ),
    ]
