# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('my_order',)},
        ),
        migrations.AddField(
            model_name='question',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
