# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20161216_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('book',)},
        ),
    ]
