# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_auto_20161216_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='my_order',
        ),
        migrations.RemoveField(
            model_name='book',
            name='my_order',
        ),
    ]
